### ISSUE TITLE
iou_matrix[d,t] = iou(det,trk) with det input not match with sort requirment (a bug?)

### ISSUE THREAD

**Issue by rambleramble** [cfotache/pytorch_objectdetecttrack#13]
Great work, thanks a lot for sharing!

Noticed this thing and seems a bug due to input format:

In original sort, the input format of det is 
Computes IOU between two bboxes in the form [x1,y1,x2,y2]

in your code, the det is in format of [x1, y1, x2, y2, object_conf, class_score, class_pred], due to the yolov3 output.

suggested change:
iou_matrix[d,t] = iou(det[:4],trk[:4])

Let me know if it makes sense or not, thanks again!

**Comment by SriramPingali** [comment]
@rambleramble The code seems to be using the first four indices anyways, so I guess it's not an issue.

**Comment by rambleramble** [comment]
Thanks and i agree, @SriramPingali

**Comment by SriramPingali** [comment]
You can deal with the issue by making a bit of change in iou function of sort.py . 
w = np.maximum(0., xx2 - xx1) to w = np.maximum(0., xx2 - xx1).float()
similarly, 
h = np.maximum(0., yy2 - yy1) to h = np.maximum(0., yy2 - yy1).float()
